githubConfigSecret:
    github_token: ENC[AES256_GCM,data:rSFEuDshemq0ptfN4KrQlK0cotolS1uloYl5biIkoGGRMSC592dtRA==,iv:gOHSC7270/ikQq7c+D4z1eBHUh2aUjtQOLY8HClV3rM=,tag:nspc8kYEn19+esd1xrlNUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wkgxl8zfy9sdy4pz4lqz930mex28uwmxckejwh7a7h7q9xu954qqgl86kg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdE1pdzJ4Skx2QS9xcUI0
            bWprNnFpZVJpNVlSd2pFUm5wN0wzV01oTHgwClVGZ0owSFhhU2RBV3ZCRHQ3cUlS
            TSt6Q0xPYTVIQ21jeGZSVHBFbUhwUkEKLS0tIFRFNVZTOGZmZUlWcG5JQVNtb0Z0
            WmRiLytKT2FTU3JsNG51dmEyN2NEd3cKTa/Dw/Erij4rrZk/4AVen1S1yFhnnNhm
            kenbohOG07bGf8OFI4Iv/JfVxFgS4IlQw6KfmqAsc9hOA9F8ohOoUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-20T20:54:15Z"
    mac: ENC[AES256_GCM,data:HES0gA7QWIt5FOCJqZznTMLhmhkgtHDL0utlhgygfanmET3YsN15cR/WyTr9QnxmeCqErLwgjtxZx2brv+vaEX7WXJFXMIpDfGuicMt0gCKWZyg0s9Z7BRgGIHLUXA+rPVuOL1Cl+eW+AWu7s0+hmyGo9S2Ty2FY13pRuU0EN2c=,iv:61L51uLHdR0KJ6kwsnm0PLvwYtHiC6XbP8xWP2LfMvs=,tag:i++l5eHv4WMKVRKJN0QcYg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
