githubConfigSecret:
    github_token: ENC[AES256_GCM,data:gt5TcASHbfMS8AKMZ5RhIkP0lHDS0imddHsdMOpFOG9/MhYkLQHtOw==,iv:l0x6HWaPQbY50ctiqYTE6ZvDTwtZAnxmWHW1AjX36/c=,tag:a0Ku63bb1Cyk4oNMHRDXdQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age135rzv8fdmtz4jz8hp4gymeyupc4az85r79tyzgv7wjus2f0mcp4ssz3cjh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZ3NjUmtVeWdoZnBiQy9m
            N3Q5MXFzY3daVWJGYWFJWFFqcmorcnpoTWhNCjliU05NT1BLQnMvMEtWbkNoT05y
            Qms2d0NqR0g1R0FleS9GQ0p3dGNGRDQKLS0tIDNLZzVpYWdFZVhablFBenFWeVVZ
            VmVSbHNjbkFFS2JkSTVDYjg2cGljV2cK8y8IL1Sb703qNX0T2WVPN4Q7AoUbm00A
            GRffKYmv4QxljyOT3IgN47anU+ONK7iclbaAWQ2MQHb1exG7HcviTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-16T20:41:10Z"
    mac: ENC[AES256_GCM,data:KM5S7TUwgwpAzY3kIjoSvYtKkQ0pvSAgSbk4jPKNmTGegSJJAxl+Kd5z4nE7kqjkzZHoYbW+VPOYY+GsYoHafXDlxHzSS0sfL+fTq/PrLrRQ2pQxP3TectTJNL6nU7oBmyAGuDV/Vsopo6nVbXMOQjCMCdljNKMIPQIW/v+XsR4=,iv:feoUqnI17zH5jUIc4mEIufoUW9RbEMJHSGrZ+q5GGg8=,tag:Hm1XFvBPXWlcOj7M3hOgQA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
